In [1]:
import pandas as pd 
import numpy as np

In [5]:
age = np.array([10,20,30])
roll_no = np.array([11,22,33])
print(age)   # the output is vector1 
print(roll_no)   # the output is vector2
# type(age)

students = np.array([
    [20,30,40],
    [10,12,13]
])

print(students)

[10 20 30]
[11 22 33]
[[20 30 40]
 [10 12 13]]


In [9]:
# student_data_row1 = np.array ([12,90])
# student_data_row2 = np.array ([14,80])
# student_data_row3 = np.array ([15,50])
student_datas = np.array([
    [12,90],
    [14,80],
    [15,50]
])   # matrix
weights = np.array([[10],[2]])

prediction = np.dot(student_datas,weights)
print(prediction)



[[300]
 [300]
 [250]]
