In [2]:
import pandas as pd 

In [3]:
df = pd.DataFrame({
    "Price" : [100,200,300]
})
df

,Price
0,100
1,200
2,300


In [5]:
print(type(df["Price"].values))

<class 'numpy.ndarray'>


In [ ]:
# install numpy
pip install numpy

In [6]:
# import numpy 
import numpy as np

In [13]:
# list 
salary = [1000,2000,3000]

# convert list to array 
salary_array = np.array(salary)
type(salary_array)

numpy.ndarray

In [14]:
new_salary_array = salary_array + 1   # vectorization
new_salary_array

array([1001, 2001, 3001])

In [19]:
s_array = np.array([100,200,300])  # one dimensional array
s_array

array([100, 200, 300])

In [20]:
# two dimensional array
data

array([[  10, 1000],
       [  20, 2000],
       [  30, 3000]])

In [23]:
# check number of dimensional
print(s_array.ndim)
print(data.ndim)

1
2


In [25]:
# shape of array (provides no of rows and columns (rows, columns) also called as (rows, features))
print(s_array.shape)
print(data.shape)

(3,)
(3, 2)


In [27]:
# total numbers of values ||| product of rows and columns
print(s_array.size)
print(data.size)

3
6


In [29]:
# data type 
# in numpy array , data must be homogeneous type 
print(data.dtype)

int64


In [32]:
# print complete row || print one dimensional value
print(data[0])

# print columns value as per index
print(data[0,1])

[  10 1000]
1000


In [39]:
# slicing data 
datas = np.array([
    [10,1001],
    [20,2001],
    [30,3001],
    [10,1002],
    [20,2002],
    [30,3002]
])

datas[:3]    # from index 0 to 2
datas[2:5]    # from index 2 to 4

array([[  30, 3001],
       [  10, 1002],
       [  20, 2002]])

In [56]:
# extract data from second columns
print(datas[:,1])

[1001 2001 3001 1002 2002 3002]
