In [1]:
import numpy as np

In [15]:
#vectorization & broadcasting
number = np.array([1,2,3,4,5])
results = number * 10
print(results > 30)
print(results > 30)
print(results)
results[(results > 30) & (results < 50)]

[False False False  True  True]
[False False False  True  True]
[10 20 30 40 50]


array([40])

In [14]:
#vectorization
price = np.array([100,200,300])
quantity = np.array([2,4,6])

price * quantity

array([ 200,  800, 1800])

In [24]:
# data reshaping and array reshaping

arr = np.array([1,2,3,4,5,6])
arr.shape

(6,)

In [23]:
arr.reshape(2,3)  #(rows, columns)

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [25]:
data = np.array([
    [1,2,3],
    [4,5,6]
])
data.shape

(2, 3)

In [26]:
data.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [37]:
# reshape in one dimesional (better method)
data.reshape(-1)    # -1 is a powerful command which makes multiple dimesional data into a flat or one dimesional data

array([1, 2, 3, 4, 5, 6])